export const ACTIONS = {
  key_press: "key_press",
  render: "render",
  player_move: "player_move",
  player_respawn: "player_respawn",
  air_update: "air_update",
  blocks_update: "blocks_update",
  blocks_take: "blocks_take",
  blocks_open: "blocks_open",
  blocks_fall: "blocks_fall",
  view_update: "view_update",
  item_take: "item_take",
};
export const BLOCKS = {
  player: "player",
  sky: "sky",
  soil: "soil",
  sand: "sand",
  trace: "trace",
  trace_active: "trace_active",
  stone: "stone",
  stone_fall: "stone_fall",
  box_art: "box_art",
  box_bonus: "box_bonus",
  box_air: "box_air",
  art: "art",
  bonus: "bonus",
};
export const BLOCK_TO_AIR_COST = {
  [BLOCKS.sky]: 100,
  [BLOCKS.soil]: -2,
  [BLOCKS.sand]: -1,
  [BLOCKS.trace]: -1,
  [BLOCKS.stone]: -5,
  [BLOCKS.stone_fall]: -20,
  [BLOCKS.box_art]: 0,
  [BLOCKS.box_bonus]: 0,
  [BLOCKS.box_air]: 20,
};
export const BLOCK_TO_COLOR = {
  [BLOCKS.player]: "blue",
  [BLOCKS.sky]: "azure",
  [BLOCKS.soil]: "sienna",
  [BLOCKS.sand]: "sandybrown",
  [BLOCKS.trace]: "darkslategrey",
  [BLOCKS.trace_active]: "black",
  [BLOCKS.stone]: "slategrey",
  [BLOCKS.stone_fall]: "red",
  [BLOCKS.box_art]: "gold",
  [BLOCKS.box_bonus]: "purple",
  [BLOCKS.box_air]: "cyan",
  [BLOCKS.art]: "gold",
  [BLOCKS.bonus]: "purple",
};
